Repository iTeam-S/Ampalibe, pull requests merged in 2022-10, with the labels that each got.

#65 Add reusable file to optimize number of send_file
  ampalibe/messenger.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#66 [FEAT] Messenger API : Manage personas
  ampalibe/messenger.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#67 [ADD] new messenger api : send receipt template
  ampalibe/messenger.py
  ampalibe/ui.py
  docs/source/messenger.rst
  tests/test_api_messenger.py
Labels: hacktoberfest-accepted
